name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build project
      run: make all

    - name: Create distribution archive
      run: make dist

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Build
        path: vireo-src.tar.gz
        compression-level: 0
        retention-days: 90
        if-no-files-found: error
